repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-added-large-files
        args: ['--maxkb=256']
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
      - id: go-mod-tidy
      - id: go-mod-vendor

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d {extends: relaxed, rules: {line-length: disable}}', '-s']
        files: \.(yaml|yml)$
        exclude: ^.helm/

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks-docker
